image: zapier/python-node:2021.12.10

stages:
  - test

.test:
  stage: test

.openapi-base:
    before_script:
        - poetry config virtualenvs.in-project true
        - poetry install
        - npm install
    extends: .test

lint:openapi:compat:
    extends: .openapi-base
    script:
        - ./bin/openapi test compatibility
    allow_failure: true

lint:openapi:checksum:
    extends: .openapi-base
    script:
        - ./bin/openapi test checksum version
