# generated by datamodel-codegen:
#   filename:  schema.yaml

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Author(BaseModel):
    name: str = Field(..., title='Name')


class Book(BaseModel):
    author: Author
    title: str = Field(..., title='Title')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class BodyCreateBookApiV1BooksPost(BaseModel):
    book: Book


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
